// Author: Papetine221
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIv9MYlg3DIqVud8oStzPzEL0nQJViSQI',
    appId: '1:959901240944:web:cd8b099813913f29c36eb5',
    messagingSenderId: '959901240944',
    projectId: 'flustockx2',
    authDomain: 'flustockx2.firebaseapp.com',
    storageBucket: 'flustockx2.firebasestorage.app',
    measurementId: 'G-02J3S7HWS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0p9QVG338YgsCFaht2gy2WDaNvfB1Zo',
    appId: '1:959901240944:android:a8e10943f4f6ed8ec36eb5',
    messagingSenderId: '959901240944',
    projectId: 'flustockx2',
    storageBucket: 'flustockx2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQDWdKCUOrVb3YikmVbHbsY1mO_WjVX4',
    appId: '1:959901240944:ios:2cd28c1e241d8eddc36eb5',
    messagingSenderId: '959901240944',
    projectId: 'flustockx2',
    storageBucket: 'flustockx2.firebasestorage.app',
    iosBundleId: 'com.example.techstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIv9MYlg3DIqVud8oStzPzEL0nQJViSQI',
    appId: '1:959901240944:web:62a8f02985b2ce1ec36eb5',
    messagingSenderId: '959901240944',
    projectId: 'flustockx2',
    authDomain: 'flustockx2.firebaseapp.com',
    storageBucket: 'flustockx2.firebasestorage.app',
    measurementId: 'G-X89XELC698',
  );
}
